import {
  copyFile,
  lstat,
  mkdir,
  readdir,
  readFile,
  writeFile
} from "node:fs/promises";
import path from "node:path";

import type {
  DeploymentAdapterCapabilities,
  DeploymentAdapterContract,
  DeploymentAdapterDescriptor,
  DeploymentContext,
  PlannedDeploymentFile,
  RuntimeLoadOrder,
  StagedDeployment,
  ValidationResult
} from "../../../shared/contracts/deployment";
import type {
  InstalledModManifestRecord,
  ModProblem,
  Profile,
  Ue4ssRuntimeInstall
} from "../../../shared/contracts/app";
import { hashFileSha256 } from "../../services/clawedModPackageService";
import { modProblem } from "../../services/packageProblems";
import { isPathInside } from "../../services/packagePaths";
import {
  listModPayloadFiles,
  stagePayloadFile
} from "../packagePayload";
import { detectUe4ssRuntimeLayout } from "../../services/ue4ssRuntimeLayout";

const adapterCapabilities: DeploymentAdapterCapabilities = {
  supportsEnableDisable: true,
  supportsOrdering: true,
  supportsExternalStorage: true,
  supportsHotChanges: false,
  requiresRestart: true,
  requiresRuntime: true
};

export class UE4SSDeploymentAdapter implements DeploymentAdapterContract {
  readonly id = "ue4ss";
  readonly version = "1";
  readonly capabilities = adapterCapabilities;
  readonly descriptor: DeploymentAdapterDescriptor = {
    id: this.id,
    label: "UE4SS Deployment Adapter",
    layer: "ue4ss",
    status: "ready",
    releaseValidation: "VALIDATED",
    capabilities: this.capabilities
  };

  async validateEnvironment(
    context: DeploymentContext
  ): Promise<ValidationResult> {
    const messages: string[] = [];

    if (!context.runtime.ue4ss) {
      messages.push("UE4SS runtime is not configured.");
    }

    if (context.runtime.status === "invalid") {
      messages.push("UE4SS runtime structure is invalid.");
    }

    if (context.runtime.status === "incompatible") {
      messages.push("UE4SS runtime is incompatible with the Clawed release build.");
    }

    if (context.loadOrder.validity === "invalid") {
      messages.push("The active profile has load-order errors.");
    }

    const enabledRecords = enabledRecordsForLoader(context);
    const payloadProblems = await validateUe4ssRecords(enabledRecords);

    if (context.runtime.status === "unvalidated") {
      messages.push(
        "UE4SS runtime is configured but unvalidated against the Clawed release build."
      );
    }

    return {
      ok:
        context.runtime.ue4ss !== null &&
        context.runtime.status !== "invalid" &&
        context.runtime.status !== "incompatible" &&
        context.loadOrder.validity !== "invalid" &&
        payloadProblems.every((problem) => problem.severity !== "error"),
      messages: [
        ...messages,
        ...payloadProblems.map((problem) => problem.message)
      ]
    };
  }

  async generateLoadOrder(
    profile: Profile,
    runtimePath?: string,
    releaseValidation: Ue4ssRuntimeInstall["releaseValidation"] = "UNVALIDATED",
    currentSteamBuildId?: string | null
  ): Promise<RuntimeLoadOrder> {
    const effectiveOrderKnown = releaseValidation === "VALIDATED";
    const selectedMods = profile.selectedMods;
    const logicalOrder = profile.orderedModIds.filter(
      (modId) => selectedMods[modId]?.enabled
    );
    const runtimeBaseline = runtimePath
      ? await readRuntimeBaselineModsTxt(runtimePath)
      : {
          entries: [],
          text: ""
        };
    const cmmModsTxt = logicalOrder.map((modId) => `${modId} : 1`).join("\n");
    const modsTxt = [
      "; Generated by Clawed Mod Manager.",
      effectiveOrderKnown
        ? `; UE4SS Lua mod startup order is validated for the packaged runtime${currentSteamBuildId ? ` on Clawed build ${currentSteamBuildId}` : ""}.`
        : "; Effective UE4SS ordering is UNVALIDATED for the Clawed release build.",
      ...(runtimeBaseline.text.length > 0
        ? [
            "",
            "; Runtime baseline entries from packaged UE4SS.",
            runtimeBaseline.text
          ]
        : []),
      ...(cmmModsTxt.length > 0
        ? [
            "",
            "; CMM profile entries.",
            cmmModsTxt
          ]
        : [])
    ].join("\n");

    return {
      logicalOrder,
      runtimeBaselineOrder: runtimeBaseline.entries,
      effectiveOrderKnown,
      messages: effectiveOrderKnown
        ? []
        : [
            "CMM translated logical order into UE4SS mods.txt deterministically.",
            "Effective Clawed runtime loading order is unvalidated."
          ],
      modsTxt: `${modsTxt}\n`
    };
  }

  async stage(context: DeploymentContext): Promise<StagedDeployment> {
    if (!context.runtime.ue4ss) {
      throw new Error("UE4SS runtime is not configured.");
    }

    const stagedFiles: PlannedDeploymentFile[] = [];
    const stagedGameRoot = path.join(context.stagingPath, "game");
    const runtimeTargetRoot = context.runtimeTargetRelativePath;
    await mkdir(stagedGameRoot, { recursive: true });

    const runtimeFiles = await listFilesRecursive(context.runtime.ue4ss.installPath);
    const runtimeLayout = detectUe4ssRuntimeLayout(
      runtimeFiles.map((runtimeFile) => ({
        relativeName: path
          .relative(context.runtime.ue4ss!.installPath, runtimeFile)
          .replaceAll("\\", "/"),
        dir: false
      }))
    );
    if (!runtimeLayout) {
      throw new Error("UE4SS runtime structure is invalid.");
    }

    for (const runtimeFile of runtimeFiles) {
      const relativePath = path.relative(
        context.runtime.ue4ss.installPath,
        runtimeFile
      );
      if (shouldSkipRuntimeFile(relativePath, runtimeLayout.modsRelativePath)) {
        continue;
      }

      const targetRelativePath = joinTargetPath(
        runtimeTargetRoot,
        relativePath
      );
      const stagedPath = path.join(stagedGameRoot, targetRelativePath);
      await mkdir(path.dirname(stagedPath), { recursive: true });
      await copyFile(runtimeFile, stagedPath);
      stagedFiles.push({
        sourcePath: stagedPath,
        targetRelativePath,
        sha256: await hashFileSha256(stagedPath)
      });
    }

    const enabledRecords = enabledRecordsForLoader(context);
    const runtimeLoadOrder = await this.generateLoadOrder(
      profileForRecords(context.profile, enabledRecords),
      context.runtime.ue4ss.installPath,
      context.runtime.ue4ss.releaseValidation,
      context.gameFingerprint.steamBuildId
    );
    const payloadProblems = await validateUe4ssRecords(enabledRecords);
    if (payloadProblems.some((problem) => problem.severity === "error")) {
      throw new Error(payloadProblems[0].message);
    }
    for (const record of enabledRecords) {
      const payloadFiles = await listModPayloadFiles(record);
      for (const payloadFile of payloadFiles) {
        if (!isUe4ssModPayload(record, payloadFile.payloadRelativePath)) {
          continue;
        }

        stagedFiles.push(
          await stagePayloadFile({
            sourcePath: payloadFile.absolutePath,
            stagedGameRoot,
            targetRelativePath: joinTargetPath(
              runtimeTargetRoot,
              rebaseUe4ssModPayload(
                payloadFile.payloadRelativePath,
                runtimeLayout.modsRelativePath
              )
            )
          })
        );
      }
    }

    const modsTxtRelativePath = joinTargetPath(
      runtimeTargetRoot,
      runtimeLayout.modsTxtRelativePath
    );
    const modsTxtPath = path.join(stagedGameRoot, modsTxtRelativePath);
    await mkdir(path.dirname(modsTxtPath), { recursive: true });
    await writeFile(modsTxtPath, runtimeLoadOrder.modsTxt);
    stagedFiles.push({
      sourcePath: modsTxtPath,
      targetRelativePath: modsTxtRelativePath,
      sha256: await hashFileSha256(modsTxtPath)
    });

    const profileConfigRelativePath = joinTargetPath(
      runtimeTargetRoot,
      runtimeLayout.profileConfigRelativePath
    );
    const profileConfigPath = path.join(stagedGameRoot, profileConfigRelativePath);
    await writeFile(
      profileConfigPath,
      `${JSON.stringify(
        {
          schemaVersion: 1,
          profileId: context.profile.id,
          generatedAt: new Date().toISOString(),
          targetSteamBuildId: context.gameFingerprint.steamBuildId,
          targetFingerprint: context.gameFingerprint.fingerprintSha256,
          effectiveOrderKnown: runtimeLoadOrder.effectiveOrderKnown,
          logicalOrder: runtimeLoadOrder.logicalOrder,
          externalPackages: enabledRecords.map((record) => ({
            id: record.manifest.id,
            version: record.manifest.version,
            loader: record.manifest.loader,
            installPath: record.mod.installPath,
            payloadPath: path.join(record.mod.installPath, "payload")
          }))
        },
        null,
        2
      )}\n`
    );
    stagedFiles.push({
      sourcePath: profileConfigPath,
      targetRelativePath: profileConfigRelativePath,
      sha256: await hashFileSha256(profileConfigPath)
    });

    return {
      adapterId: this.id,
      adapterVersion: this.version,
      profileId: context.profile.id,
      stagedPath: context.stagingPath,
      files: dedupePlannedFiles(stagedFiles),
      runtimeConfiguration: {
        type: "ue4ss",
        releaseValidation: context.runtime.ue4ss.releaseValidation,
        targetSteamBuildId: context.gameFingerprint.steamBuildId,
        targetFingerprint: context.gameFingerprint.fingerprintSha256,
        runtimeTargetRelativePath: runtimeTargetRoot,
        runtimeLayout: runtimeLayout.variant,
        runtimeModsRelativePath: path.normalize(runtimeLayout.modsRelativePath),
        effectiveOrderKnown: runtimeLoadOrder.effectiveOrderKnown,
        runtimeBaselineOrder: runtimeLoadOrder.runtimeBaselineOrder,
        logicalOrder: runtimeLoadOrder.logicalOrder,
        messages: runtimeLoadOrder.messages
      },
      sourcePackages: enabledRecords.map((record) => ({
        id: record.manifest.id,
        version: record.manifest.version,
        sha256: record.mod.sha256,
        file: record.mod.packagePath
      })),
      messages: runtimeLoadOrder.messages
    };
  }
}

async function listFilesRecursive(root: string): Promise<string[]> {
  const entries = await readdir(root, { withFileTypes: true });
  const files: string[] = [];

  for (const entry of entries) {
    const entryPath = path.join(root, entry.name);
    const entryInfo = await lstat(entryPath);
    if (!isPathInside(root, entryPath) || entryInfo.isSymbolicLink()) {
      continue;
    }

    if (entry.isDirectory()) {
      files.push(...(await listFilesRecursive(entryPath)));
    } else if (entry.isFile()) {
      files.push(entryPath);
    }
  }

  return files;
}

function shouldSkipRuntimeFile(
  relativePath: string,
  modsRelativePath: string
): boolean {
  const normalized = relativePath.replaceAll("\\", "/").toLowerCase();
  const normalizedModsPath = modsRelativePath.replaceAll("\\", "/").toLowerCase();
  return (
    normalized === `${normalizedModsPath}/mods.txt` ||
    normalized === `${normalizedModsPath}/cmm-profile.json`
  );
}

function rebaseUe4ssModPayload(
  payloadRelativePath: string,
  modsRelativePath: string
): string {
  const normalized = payloadRelativePath.replaceAll("\\", "/");
  const modsPrefix = "Mods/";
  if (!normalized.toLowerCase().startsWith(modsPrefix.toLowerCase())) {
    return payloadRelativePath;
  }

  return path.join(modsRelativePath, normalized.slice(modsPrefix.length));
}

function joinTargetPath(
  rootRelativePath: string | null,
  childRelativePath: string
): string {
  return rootRelativePath
    ? path.join(rootRelativePath, childRelativePath)
    : path.normalize(childRelativePath);
}

async function validateUe4ssRecords(
  records: InstalledModManifestRecord[]
): Promise<ModProblem[]> {
  const problems: ModProblem[] = [];

  for (const record of records) {
    const payloadFiles = await listModPayloadFiles(record);
    if (
      !payloadFiles.some((payloadFile) =>
        isUe4ssModPayload(record, payloadFile.payloadRelativePath)
      )
    ) {
      problems.push(
        modProblem(
          "error",
          "UE4SS_PAYLOAD_NOT_STRUCTURED",
          `${record.manifest.name} must contain deployable files under payload/Mods/${record.manifest.id}/.`
        )
      );
    }
  }

  return problems;
}

function isUe4ssModPayload(
  record: InstalledModManifestRecord,
  relativePath: string
): boolean {
  const normalized = relativePath.replaceAll("\\", "/").toLowerCase();
  const expectedPrefix = `mods/${record.manifest.id.toLowerCase()}/`;
  return normalized.startsWith(expectedPrefix);
}

function enabledRecordsForLoader(
  context: DeploymentContext
): InstalledModManifestRecord[] {
  return context.installedMods.filter(
    (record) =>
      record.manifest.loader === "ue4ss" &&
      context.profile.selectedMods[record.manifest.id]?.enabled === true &&
      context.profile.selectedMods[record.manifest.id]?.version ===
        record.manifest.version
  );
}

function profileForRecords(
  profile: Profile,
  records: InstalledModManifestRecord[]
): Profile {
  const recordIds = new Set(records.map((record) => record.manifest.id));
  const selectedMods = Object.fromEntries(
    Object.entries(profile.selectedMods).map(([modId, selection]) => [
      modId,
      {
        ...selection,
        enabled: selection.enabled && recordIds.has(modId)
      }
    ])
  );

  return {
    ...profile,
    selectedMods,
    orderedModIds: profile.orderedModIds.filter((modId) => recordIds.has(modId))
  };
}

async function readRuntimeBaselineModsTxt(runtimePath: string): Promise<{
  entries: string[];
  text: string;
}> {
  const runtimeFiles = await listFilesRecursive(runtimePath);
  const runtimeLayout = detectUe4ssRuntimeLayout(
    runtimeFiles.map((runtimeFile) => ({
      relativeName: path.relative(runtimePath, runtimeFile).replaceAll("\\", "/"),
      dir: false
    }))
  );
  const modsTxtPath = path.join(
    runtimePath,
    runtimeLayout?.modsTxtRelativePath ?? path.join("Mods", "mods.txt")
  );

  try {
    const rawText = await readFile(modsTxtPath, "utf8");
    const text = rawText.trim();
    return {
      entries: text
        .split(/\r?\n/)
        .map((line) => line.trim())
        .filter((line) => line.length > 0 && !line.startsWith(";"))
        .map((line) => line.split(":")[0]?.trim() ?? "")
        .filter((entry) => entry.length > 0),
      text
    };
  } catch {
    return {
      entries: [],
      text: ""
    };
  }
}

function dedupePlannedFiles(
  files: PlannedDeploymentFile[]
): PlannedDeploymentFile[] {
  const seen = new Set<string>();
  const deduped: PlannedDeploymentFile[] = [];

  for (const file of files) {
    const key = file.targetRelativePath.toLowerCase();
    if (!seen.has(key)) {
      seen.add(key);
      deduped.push(file);
    }
  }

  return deduped;
}
