import path from "node:path";

import { createClawedModFixture } from "../../tests/helpers/clawedModFixture";

export const visibleModId = "CMMVisibleValidation";
export const visibleMessage = "CMM VISIBLE VALIDATION MOD ACTIVE";

export function visibleValidationMarkers(): string[] {
  return [
    `Starting Lua mod '${visibleModId}'`,
    `[${visibleModId}] visible|enable_screen_messages|true`,
    `[${visibleModId}] visible|print_string|true`,
    `[${visibleModId}] visible|stat_unit|true`,
    `[${visibleModId}] visible|console_visual_cvars|true`,
    `[${visibleModId}] visible|debug_sphere|true`,
    `[${visibleModId}] visible|debug_line|true`,
    `[${visibleModId}] visible|debug_string|true`,
    `[${visibleModId}] visible|widget_render_initial|true`,
    `[${visibleModId}] done|${visibleMessage}`
  ];
}

export async function createVisibleValidationFixture(evidenceRoot: string) {
  return createClawedModFixture(
    path.join(evidenceRoot, "fixtures", "CMMVisibleValidation.clawedmod"),
    {
      manifest: {
        id: visibleModId,
        name: "CMM Visible Validation",
        version: timestampForVersion(),
        author: "Clawed Mod Manager",
        description:
          "UE4SS validation mod that displays an on-screen marker in Clawed.",
        loader: "ue4ss"
      },
      payloadText: visibleValidationLua()
    }
  );
}

function visibleValidationLua(): string {
  return [
    'local UEHelpers = require("UEHelpers")',
    `local marker = "[${visibleModId}] "`,
    "local function log(event, value)",
    '    print(marker .. event .. "|" .. tostring(value))',
    "end",
    "",
    "local function is_valid(object)",
    "    return object ~= nil and object.IsValid ~= nil and object:IsValid()",
    "end",
    "",
    "local function find_world_context()",
    "    local world = UEHelpers.GetWorld()",
    "    if is_valid(world) then return world end",
    '    world = FindFirstOf("World")',
    "    if is_valid(world) then return world end",
    '    local engine = FindFirstOf("GameEngine")',
    "    if is_valid(engine) then return engine end",
    "    return nil",
    "end",
    "",
    "local function safe_visible_effect(name, callback)",
    "    local ok, err = pcall(callback)",
    '    log("visible", name .. "|" .. tostring(ok) .. "|" .. tostring(err))',
    "    return ok",
    "end",
    "",
    "local function emit_visible_marker()",
    "    local kismet = UEHelpers.GetKismetSystemLibrary()",
    "    if not is_valid(kismet) then",
    '        log("visible", "kismet_invalid")',
    "        return false",
    "    end",
    "    local worldContext = find_world_context()",
    "    if worldContext == nil then",
    '        log("visible", "world_context_missing")',
    "        return false",
    "    end",
    "    local playerController = UEHelpers.GetPlayerController()",
    "    local kismetMath = UEHelpers.GetKismetMathLibrary()",
    "    local color = { R = 0.0, G = 1.0, B = 0.2, A = 1.0 }",
    `    local message = "${visibleMessage}"`,
    '    local key = UEHelpers.FindOrAddFName("CMMVisibleValidation")',
    "    local visibleEffects = 0",
    '    if safe_visible_effect("enable_screen_messages", function()',
    '        kismet:ExecuteConsoleCommand(worldContext, "EnableAllScreenMessages", playerController)',
    "    end) then visibleEffects = visibleEffects + 1 end",
    '    if safe_visible_effect("print_string", function()',
    "        kismet:PrintString(worldContext, message, true, true, color, 60.0, key)",
    "    end) then visibleEffects = visibleEffects + 1 end",
    '    if safe_visible_effect("stat_unit", function()',
    '        kismet:ExecuteConsoleCommand(worldContext, "stat unit", playerController)',
    "    end) then visibleEffects = visibleEffects + 1 end",
    '    if safe_visible_effect("console_visual_cvars", function()',
    "        local commands = {",
    '            "r.ScreenPercentage 35",',
    '            "r.TonemapperGamma 4.0",',
    '            "r.Tonemapper.Sharpen 10",',
    '            "r.PostProcessAAQuality 0",',
    '            "showflag.PostProcessing 0"',
    "        }",
    "        for _, command in ipairs(commands) do",
    "            kismet:ExecuteConsoleCommand(worldContext, command, playerController)",
    "        end",
    "    end) then visibleEffects = visibleEffects + 1 end",
    '    if safe_visible_effect("client_message", function()',
    "        playerController:ClientMessage(message, key, 60.0)",
    "    end) then visibleEffects = visibleEffects + 1 end",
    "    local function player_marker_location()",
    "        local pawn = UEHelpers.GetPlayer()",
    "        if is_valid(pawn) then",
    "            local origin = pawn:K2_GetActorLocation()",
    "            return kismetMath:Add_VectorVector(origin, { X = 0.0, Y = 0.0, Z = 160.0 })",
    "        end",
    "        if is_valid(playerController) and is_valid(playerController.PlayerCameraManager) then",
    "            local camera = playerController.PlayerCameraManager",
    "            local cameraLocation = camera:GetCameraLocation()",
    "            local forward = kismetMath:GetForwardVector(camera:GetCameraRotation())",
    "            local offset = kismetMath:Multiply_VectorInt(forward, 450)",
    "            return kismetMath:Add_VectorVector(cameraLocation, offset)",
    "        end",
    '        error("no player or camera marker location")',
    "    end",
    '    if safe_visible_effect("debug_sphere", function()',
    "        kismet:DrawDebugSphere(worldContext, player_marker_location(), 220.0, 24, color, 60.0, 24.0)",
    "    end) then visibleEffects = visibleEffects + 1 end",
    '    if safe_visible_effect("debug_line", function()',
    "        local startLocation = player_marker_location()",
    "        local endLocation = kismetMath:Add_VectorVector(startLocation, { X = 0.0, Y = 0.0, Z = 650.0 })",
    "        kismet:DrawDebugLine(worldContext, startLocation, endLocation, color, 60.0, 32.0)",
    "    end) then visibleEffects = visibleEffects + 1 end",
    '    if safe_visible_effect("debug_string", function()',
    "        kismet:DrawDebugString(worldContext, player_marker_location(), message, nil, color, 60.0)",
    "    end) then visibleEffects = visibleEffects + 1 end",
    "    local function build_text_value()",
    "        local textValue = nil",
    "        local textOk = pcall(function()",
    "            textValue = FText(message)",
    "        end)",
    "        if not textOk or textValue == nil then",
    "            local textLibrary = UEHelpers.GetKismetTextLibrary()",
    '            if not is_valid(textLibrary) then error("text library invalid") end',
    "            textValue = textLibrary:Conv_StringToText(message)",
    "        end",
    "        return textValue",
    "    end",
    "    local function set_text_block_text(block, textValue)",
    "        if not is_valid(block) then return false end",
    "        local ok = pcall(function()",
    "            block:SetText(textValue)",
    "        end)",
    "        return ok",
    "    end",
    "    local function mutate_widget_render(widget)",
    "        if not is_valid(widget) then return false end",
    "        local changed = false",
    "        local ok = pcall(function() widget:SetRenderOpacity(0.45) end)",
    "        if ok then changed = true end",
    "        ok = pcall(function() widget:SetRenderScale({ X = 1.08, Y = 1.08 }) end)",
    "        if ok then changed = true end",
    "        ok = pcall(function() widget:SetRenderTransformAngle(4.0) end)",
    "        if ok then changed = true end",
    "        return changed",
    "    end",
    "    local function apply_widget_render_mutation(label)",
    '        local widgetClasses = { "Widget", "UserWidget", "TextBlock", "Image", "Button", "CanvasPanel", "Border" }',
    "        local changed = 0",
    "        for _, className in ipairs(widgetClasses) do",
    "            local widgets = FindAllOf(className)",
    "            if widgets ~= nil then",
    "                for _, widget in pairs(widgets) do",
    "                    if mutate_widget_render(widget) then changed = changed + 1 end",
    "                end",
    "            end",
    "        end",
    '        if changed == 0 then error("no widgets accepted render mutation") end',
    '        log("visible", "widget_render_" .. label .. "|true|" .. tostring(changed))',
    "        return true",
    "    end",
    "    local function apply_text_blocks(label)",
    "        local textValue = build_text_value()",
    '        local blocks = FindAllOf("TextBlock")',
    '        if blocks == nil then error("no TextBlock objects found") end',
    "        local changed = 0",
    "        for _, block in pairs(blocks) do",
    "            if set_text_block_text(block, textValue) then changed = changed + 1 end",
    "        end",
    '        if changed == 0 then error("no TextBlock widgets accepted SetText") end',
    '        log("visible", "text_blocks_" .. label .. "|true|" .. tostring(changed))',
    "        return true",
    "    end",
    '    if safe_visible_effect("text_blocks_initial", function()',
    '        apply_text_blocks("initial")',
    "    end) then visibleEffects = visibleEffects + 1 end",
    '    if safe_visible_effect("widget_render_initial", function()',
    '        apply_widget_render_mutation("initial")',
    "    end) then visibleEffects = visibleEffects + 1 end",
    '    safe_visible_effect("text_block_notify", function()',
    '        NotifyOnNewObject("/Script/UMG.TextBlock", function(block)',
    "            local ok, textValue = pcall(build_text_value)",
    "            if ok then set_text_block_text(block, textValue) end",
    "        end)",
    "    end)",
    "    local function schedule_text_refresh(delayMs, label)",
    '        safe_visible_effect("schedule_" .. label, function()',
    "            ExecuteWithDelay(delayMs, function()",
    "                ExecuteInGameThread(function()",
    "                    local ok, err = pcall(function() apply_text_blocks(label) end)",
    '                    if not ok then log("visible", "text_blocks_" .. label .. "|false|" .. tostring(err)) end',
    "                    ok, err = pcall(function() apply_widget_render_mutation(label) end)",
    '                    if not ok then log("visible", "widget_render_" .. label .. "|false|" .. tostring(err)) end',
    "                end)",
    "            end)",
    "        end)",
    "    end",
    '    schedule_text_refresh(1500, "delayed_1500")',
    '    schedule_text_refresh(4000, "delayed_4000")',
    '    schedule_text_refresh(7000, "delayed_7000")',
    '    if safe_visible_effect("scale_pawn", function()',
    "        local pawn = UEHelpers.GetPlayer()",
    '        if not is_valid(pawn) then error("pawn invalid") end',
    "        pawn:SetActorScale3D({ X = 1.7, Y = 1.7, Z = 1.7 })",
    "    end) then visibleEffects = visibleEffects + 1 end",
    '    log("visible", "effect_count|" .. tostring(visibleEffects))',
    "    return visibleEffects > 0",
    "end",
    "",
    "ExecuteInGameThread(function()",
    '    local engine = FindFirstOf("GameEngine")',
    '    log("engine", tostring(engine ~= nil))',
    "    local visible = emit_visible_marker()",
    `    log("done", visible and "${visibleMessage}" or "visible marker failed")`,
    "end)"
  ].join("\n");
}

function timestampForVersion(): string {
  return new Date()
    .toISOString()
    .replaceAll("-", "")
    .replaceAll(":", "")
    .replace(/\.\d{3}Z$/, "");
}
